baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Jim Grundy'

[[menus.main]]
name = 'About'
pageRef = '/page/about'
weight = 10

[[menus.main]]
name = 'Paintings'
pageRef = '/paintings'
weight = 20

[[menus.main]]
name = 'Exhibitions'
pageRef = '/page/exhibitions'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/page/contact'
weight = 30


[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
